name: Deploy version

###
### Release branch deployer
###

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  extract-tag:
    uses: UpStreamPay/usp-reusable-workflows/.github/workflows/utils-gitflow-extract-from-ref.yaml@reusable-v0
    with:
      strip-tag-prefix: 'v'

  build-and-push:
    needs: [extract-tag]
    uses: UpStreamPay/usp-reusable-workflows/.github/workflows/build-and-push-maven-gcp-gar-plugin.yaml@reusable-v0
    with:
      java-version: "17"
      java-distribution: "adopt"
      profile: "prod-repository"
      workload-identity-provider: ${{ vars.GCP_PROD_PLUGINS_WORKLOAD_IDENTITY_PROVIDER }}
      service-account: ${{ vars.GCP_PROD_PLUGINS_MAVEN_REGISTRY_SA_EMAIL }}
      gar-maven-repository-name: ${{ vars.GCP_PROD_PLUGINS_MAVEN_REGISTRY_NAME }}
      gar-maven-location: ${{ vars.GCP_PROD_PLUGINS_MAVEN_REGISTRY_LOCATION }}
    secrets:
      D4_GITHUB_PLUGIN_USERNAME: ${{ secrets.PLUGIN_D4_USERNAME }}
      D4_GITHUB_PLUGIN_PASSWORD: ${{ secrets.PLUGIN_D4_PASSWORD }}

  deploy-plugin:
    needs: [extract-tag, build-and-push]
    uses: UpStreamPay/usp-reusable-workflows/.github/workflows/utils-gitflow-deploy-plugin.yaml@reusable-v0
    with:
      gar-region: ${{ vars.GCP_PROD_PLUGINS_MAVEN_REGISTRY_LOCATION }}
      gar-project: ${{ vars.GCP_PROD_PLUGINS_PROJECT_ID }}
      gar-repository: ${{ vars.GCP_PROD_PLUGINS_MAVEN_REGISTRY_NAME }}
      group-id: ${{ vars.MAVEN_GROUP_ID }}
      artifact-id: ${{ vars.MAVEN_ARTIFACT_ID }}
      version: ${{ needs.extract-tag.outputs.tag }}
      bucket-name: ${{ vars.GCP_PREPROD_PLUGINS_BUCKET_PLUGINS_NAME }}
      bucket-path: plugins/
      existing-bucket-path: plugins-archives/
      pull-gar-service-account: ${{ vars.GCP_PROD_PLUGINS_MAVEN_REGISTRY_SA_EMAIL }}
      pull-gar-workload-identity-provider: ${{ vars.GCP_PROD_PLUGINS_WORKLOAD_IDENTITY_PROVIDER }}
      push-bucket-service-account: ${{ vars.GCP_PREPROD_PLUGINS_PUSH_BUCKET_PLUGINS_SA_EMAIL }}
      push-bucket-workload-identity-provider:  ${{ vars.GCP_PREPROD_PLUGINS_WORKLOAD_IDENTITY_PROVIDER }}
