name: Release Manager

##
## Release Manager
##

on:
  push:
    branches:
      - main

jobs:
  release-manager:
    uses: UpStreamPay/usp-reusable-workflows/.github/workflows/release-manager.yaml@reusable-v0
    with:
      pre-commit: scripts/cc-pre-commit.js
    secrets:
      GITHUB_ACCESS_TOKEN: ${{ secrets.USP_GITHUB_ADMIN_ACCES_TOKEN }}
  
  send-slack-message:
    needs: ["release-manager"]
    if: needs.release-manager.outputs.skipped == 'false'
    uses: UpStreamPay/usp-reusable-workflows/.github/workflows/utils-gitflow-new-release-slack-message.yaml@reusable-v0
    with:
      channel-id: ${{ vars.SLACK_NEW_RELEASE_PLUGIN_CHANNEL }}
      version: ${{ needs.release-manager.outputs.version }}
      type: Official Release
      release-url: ${{ needs.release-manager.outputs.release-url }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.USP_SLACK_TOKEN }}
