name: Execute e2e tests

on:
  workflow_dispatch:
    inputs:
      target-environment:
        description: "Environment on which tests will be executed"
        required: true
        default: "test"
        type: choice
        options:
          - dev
          - test
          - preprod

jobs:
  tests-e2e:
    uses: UpStreamPay/usp-reusable-workflows/.github/workflows/plugin-e2e-tests.yaml@reusable-v0
    with:
      filter-tags: ${{ vars.E2E_TESTS_FILTER }}
      target-environment: ${{ inputs.target-environment }}
      channel-id: ${{ vars.SLACK_TESTS_PLUGIN_CHANNEL }}
    secrets:
      GITHUB_ACCESS_TOKEN: ${{ secrets.USP_GITHUB_ADMIN_ACCES_TOKEN }}
      ENV_FILE: ${{ secrets.PLUGINS_E2E_BASE64_ENV_FILE }}
      SLACK_BOT_TOKEN: ${{ secrets.USP_SLACK_TOKEN }}
